### ISSUE TITLE
Grass, Trees and Water

### ISSUE THREAD

**Issue by salmjak** [FabioZumbi12/Sponge-RedProtect-18#12]
Outside of protected areas (wilderness) grass will not spread, trees won't grow and water does not flow.

Don't know if this is an intentional feature or not, but I can't find any config options for it so I doubt it.

**Comment by FabioZumbi12** [comment]
Not, is not intentional, but i see on my server the grow of grass and tree depends of the ammount of players online and server TPS, the same with water and lava flow. is not because redprotect.
